# Generated by Django 4.2.13 on 2024-08-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cnic_number',
            field=models.CharField(default='DEFAULT_CNIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='fee_status',
            field=models.IntegerField(),
        ),
    ]
