# Generated by Django 4.2.13 on 2024-08-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_member_cnic_number_alter_member_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cnic_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
