# Generated by Django 4.2.13 on 2024-08-16 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_member_fee_status_feepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
