# Generated by Django 4.2.13 on 2024-08-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_member_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
