# Generated by Django 4.2.13 on 2024-08-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_alter_member_monthly_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmember',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
